/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meshes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a mesh (STL/OBJ/3MF, multipart field `file`) */
        post: operations["upload_mesh_api_meshes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meshes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mesh info by id */
        get: operations["mesh_get_api_meshes__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meshes/{id}/buffer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Render buffer for the viewport */
        get: operations["mesh_buffer_api_meshes__id__buffer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meshes/{id}/adjacency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Face adjacency for flat-face grow */
        get: operations["mesh_adjacency_api_meshes__id__adjacency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meshes/{id}/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coplanar face groups, area-sorted (agents pick by id) */
        get: operations["mesh_facets_api_meshes__id__facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meshes/{id}/facets/{facet_id}/faces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Triangle ids of one facet (GUI highlight; STEP meshes ignore angle_deg) */
        get: operations["mesh_facet_faces_api_meshes__id__facets__facet_id__faces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meshes/{id}/preview.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** PNG render so an agent can look at the model */
        get: operations["mesh_preview_api_meshes__id__preview_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create a project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project */
        get: operations["get_project_api_projects__id__get"];
        /** Replace a project */
        put: operations["update_project_api_projects__id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/voxelize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voxelize the project and report grid statistics */
        post: operations["voxelize_project_api_projects__id__voxelize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/resolve-selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a selection to full-grid nodes (preview capped at 5000 points) */
        post: operations["resolve_selection_api_projects__id__resolve_selection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Start a run for a project */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a run */
        post: operations["cancel_run_api_runs__id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/result.stl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the result as STL (trim=true: intersected with the design mesh) */
        get: operations["result_stl_api_runs__id__result_stl_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/result.vti": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the density field as VTI */
        get: operations["result_vti_api_runs__id__result_vti_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/result.npz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the density field as NPZ */
        get: operations["result_npz_api_runs__id__result_npz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/stress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Von Mises stress field of the final design */
        get: operations["result_stress_api_runs__id__stress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/project.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project + run record (reloadable, re-runnable headlessly) */
        get: operations["run_project_api_runs__id__project_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run status */
        get: operations["get_run_api_runs__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/preview.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** PNG render of the result so an agent can look at it */
        get: operations["run_preview_api_runs__id__preview_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_mesh_api_meshes_post */
        Body_upload_mesh_api_meshes_post: {
            /** File */
            file: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /**
         * FaceSelection
         * @description Explicit triangle ids (what the GUI produces by clicking/painting).
         */
        FaceSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "faces";
            /** Mesh Id */
            mesh_id: string;
            /** Face Ids */
            face_ids: number[];
        };
        /**
         * FacetFaces
         * @description Triangle ids (of GET /meshes/{id}/buffer) that make up one facet.
         */
        FacetFaces: {
            /** Face Ids */
            face_ids: number[];
        };
        /** FacetInfo */
        FacetInfo: {
            /** Id */
            id: number;
            /** N Faces */
            n_faces: number;
            /** Area */
            area: number;
            /** Normal */
            normal: number[];
            /** Centroid */
            centroid: number[];
            /** Bbox */
            bbox: number[][];
            /**
             * Kind
             * @default other
             * @enum {string}
             */
            kind: "plane" | "cylinder" | "other";
            /** Axis */
            axis?: number[] | null;
            /** Radius */
            radius?: number | null;
            /** Brep Face */
            brep_face?: number | null;
        };
        /**
         * FacetSelection
         * @description Coplanar facet ids from GET /api/meshes/{id}/facets (agent-friendly, stable per angle_deg).
         */
        FacetSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "facets";
            /** Mesh Id */
            mesh_id: string;
            /** Facet Ids */
            facet_ids: number[];
            /**
             * Angle Deg
             * @default 5
             */
            angle_deg: number;
        };
        /** GridSpec */
        GridSpec: {
            /**
             * Elements Along Longest
             * @default 60
             */
            elements_along_longest: number;
            /**
             * Padding
             * @default 1
             */
            padding: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** IterationRecord */
        IterationRecord: {
            /** It */
            it: number;
            /** Compliance */
            compliance: number;
            /** Volume */
            volume: number;
            /** Change */
            change: number;
            /** T Iter */
            t_iter: number;
            /**
             * Stress Max
             * @default null
             */
            stress_max: number | null;
            /**
             * Constraint
             * @default null
             */
            constraint: number | null;
        };
        /** LoadSpec */
        LoadSpec: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Selection */
            selection: components["schemas"]["FaceSelection"] | components["schemas"]["FacetSelection"] | components["schemas"]["NormalSelection"] | components["schemas"]["PlaneSelection"] | components["schemas"]["PrimitiveSelection"];
            /** Force */
            force: number[];
            /**
             * Case
             * @default 0
             */
            case: number;
        };
        /** MaterialSpec */
        MaterialSpec: {
            /**
             * E
             * @default 1
             */
            E: number;
            /**
             * Nu
             * @default 0.3
             */
            nu: number;
        };
        /** MeshFacets */
        MeshFacets: {
            /** Mesh Id */
            mesh_id: string;
            /** Angle Deg */
            angle_deg: number;
            /** Facets */
            facets: components["schemas"]["FacetInfo"][];
            /** N Facets Total */
            n_facets_total: number;
        };
        /** MeshInfo */
        MeshInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** N Faces */
            n_faces: number;
            /** N Vertices */
            n_vertices: number;
            /** Bbox */
            bbox: number[][];
            /** Is Watertight */
            is_watertight: boolean;
            /** Volume */
            volume?: number | null;
            /**
             * Source
             * @default mesh
             * @enum {string}
             */
            source: "mesh" | "step";
            /** N Brep Faces */
            n_brep_faces?: number | null;
        };
        /** MeshRef */
        MeshRef: {
            /** Mesh Id */
            mesh_id?: string | null;
            /** Path */
            path?: string | null;
            /** Transform */
            transform?: number[];
        };
        /**
         * NormalSelection
         * @description All surface faces whose normal is within angle_deg of `direction`, optionally clipped to a world bbox.
         */
        NormalSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "normal";
            /** Mesh Id */
            mesh_id: string;
            /** Direction */
            direction: number[];
            /**
             * Angle Deg
             * @default 10
             */
            angle_deg: number;
            /**
             * Within
             * @default null
             */
            within: number[][] | null;
        };
        /** ParamsSpec */
        ParamsSpec: {
            /**
             * Volfrac
             * @default 0.3
             */
            volfrac: number;
            /**
             * Penal
             * @default 3
             */
            penal: number;
            /**
             * Rmin
             * @default 2
             */
            rmin: number;
            /**
             * Max Iter
             * @default 100
             */
            max_iter: number;
            /**
             * Tol
             * @default 0.01
             */
            tol: number;
            /**
             * Move
             * @default 0.2
             */
            move: number;
            /**
             * Heaviside
             * @default false
             */
            heaviside: boolean;
            /**
             * Continuation
             * @default false
             */
            continuation: boolean;
            /**
             * Solver
             * @default auto
             * @enum {string}
             */
            solver: "auto" | "amg" | "direct";
            /**
             * Dtype
             * @default float64
             * @enum {string}
             */
            dtype: "float64" | "float32";
            /**
             * Density Every
             * @default 1
             */
            density_every: number;
            /**
             * Optimizer
             * @default oc
             * @enum {string}
             */
            optimizer: "oc" | "mma";
            /** Symmetry */
            symmetry?: components["schemas"]["SymmetrySpec"][];
            /** Stress Limit */
            stress_limit?: number | null;
            /**
             * Stress Pnorm
             * @default 8
             */
            stress_pnorm: number;
            /** Overhang */
            overhang?: ("+x" | "-x" | "+y" | "-y" | "+z" | "-z") | null;
        };
        /**
         * PlaneSelection
         * @description Surface grid nodes within `tol` of the plane (no mesh needed). Agent-friendly: 'fix the plane x=0'.
         */
        PlaneSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "plane";
            /** Point */
            point: number[];
            /** Normal */
            normal: number[];
            /**
             * Tol
             * @default 0
             */
            tol: number;
        };
        /** PrimitiveSelection */
        PrimitiveSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "box" | "sphere" | "cylinder";
            /** Transform */
            transform?: number[];
            /** Size */
            size?: number[];
            /**
             * Surface Only
             * @default true
             */
            surface_only: boolean;
        };
        /** Project */
        Project: {
            /**
             * Name
             * @default untitled
             */
            name: string;
            design_mesh?: components["schemas"]["MeshRef"] | null;
            /** Ref Models */
            ref_models?: components["schemas"]["RefModel"][];
            grid?: components["schemas"]["GridSpec"];
            material?: components["schemas"]["MaterialSpec"];
            params?: components["schemas"]["ParamsSpec"];
            /** Loads */
            loads?: components["schemas"]["LoadSpec"][];
            /** Supports */
            supports?: components["schemas"]["SupportSpec"][];
            /** Id */
            id: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ProjectIn */
        ProjectIn: {
            /**
             * Name
             * @default untitled
             */
            name: string;
            design_mesh?: components["schemas"]["MeshRef"] | null;
            /** Ref Models */
            ref_models?: components["schemas"]["RefModel"][];
            grid?: components["schemas"]["GridSpec"];
            material?: components["schemas"]["MaterialSpec"];
            params?: components["schemas"]["ParamsSpec"];
            /** Loads */
            loads?: components["schemas"]["LoadSpec"][];
            /** Supports */
            supports?: components["schemas"]["SupportSpec"][];
        };
        /** RefModel */
        RefModel: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Mesh Id */
            mesh_id?: string | null;
            /** Path */
            path?: string | null;
            /** Transform */
            transform?: number[];
            /**
             * Mode
             * @default keep_out
             * @enum {string}
             */
            mode: "keep_in" | "keep_out";
            /**
             * Visible
             * @default true
             */
            visible: boolean;
        };
        /** ResolvedNodes */
        ResolvedNodes: {
            /** Count */
            count: number;
            /** Xyz */
            xyz: number[][];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** RunCreate */
        RunCreate: {
            /** Project Id */
            project_id: string;
        };
        /**
         * RunExport
         * @description GET /api/runs/{id}/project.json: everything needed to reload or re-run headlessly.
         */
        RunExport: {
            project: components["schemas"]["Project"];
            run: components["schemas"]["RunInfo"];
        };
        /** RunInfo */
        RunInfo: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "error" | "cancelled";
            /** Created At */
            created_at: string;
            /**
             * Finished At
             * @default null
             */
            finished_at: string | null;
            /** History */
            history?: components["schemas"]["IterationRecord"][];
            /** @default null */
            stats: components["schemas"]["VoxelStats"] | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Outcome
             * @default null
             */
            outcome: ("converged" | "max_iter" | "cancelled" | "error") | null;
            /**
             * Message
             * @default null
             */
            message: string | null;
        };
        /** SupportSpec */
        SupportSpec: {
            /** Id */
            id: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Selection */
            selection: components["schemas"]["FaceSelection"] | components["schemas"]["FacetSelection"] | components["schemas"]["NormalSelection"] | components["schemas"]["PlaneSelection"] | components["schemas"]["PrimitiveSelection"];
            /** Fix */
            fix?: boolean[];
        };
        /** SymmetrySpec */
        SymmetrySpec: {
            /**
             * Axis
             * @enum {string}
             */
            axis: "x" | "y" | "z";
            /** Position */
            position?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoxelStats */
        VoxelStats: {
            /** Nx */
            nx: number;
            /** Ny */
            ny: number;
            /** Nz */
            nz: number;
            /** H */
            h: number;
            /** Origin */
            origin: number[];
            /** N Active */
            n_active: number;
            /** N Free */
            n_free: number;
            /** N Passive Solid */
            n_passive_solid: number;
            /** N Passive Void */
            n_passive_void: number;
            /** N Nodes */
            n_nodes: number;
            /** N Dof */
            n_dof: number;
            /** Est Bytes */
            est_bytes: number;
            /** Est Sec Per Iter */
            est_sec_per_iter: number;
            /** Warnings */
            warnings?: string[];
        };
        /** ProgressMsg */
        ProgressMsg: {
            /** It */
            it: number;
            /** Compliance */
            compliance: number;
            /** Volume */
            volume: number;
            /** Change */
            change: number;
            /** T Iter */
            t_iter: number;
            /**
             * Stress Max
             * @default null
             */
            stress_max: number | null;
            /**
             * Constraint
             * @default null
             */
            constraint: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "progress";
        };
        /** StatusMsg */
        StatusMsg: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cancelled" | "done" | "error" | "started";
            /**
             * Message
             * @default null
             */
            message: string | null;
            /** @default null */
            run: components["schemas"]["RunInfo"] | null;
        };
        WsMessage: components["schemas"]["ProgressMsg"] | components["schemas"]["StatusMsg"];
        Selection: components["schemas"]["FaceSelection"] | components["schemas"]["FacetSelection"] | components["schemas"]["NormalSelection"] | components["schemas"]["PlaneSelection"] | components["schemas"]["PrimitiveSelection"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_mesh_api_meshes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_mesh_api_meshes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeshInfo"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mesh_get_api_meshes__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeshInfo"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mesh_buffer_api_meshes__id__buffer_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description [u32 n_vert][u32 n_tri][f32 xyz*n_vert][u32 ijk*n_tri][f32 nxyz per face], little-endian */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mesh_adjacency_api_meshes__id__adjacency_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description u32 pairs of adjacent face ids (trimesh.face_adjacency) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mesh_facets_api_meshes__id__facets_get: {
        parameters: {
            query?: {
                angle_deg?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeshFacets"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mesh_facet_faces_api_meshes__id__facets__facet_id__faces_get: {
        parameters: {
            query?: {
                angle_deg?: number;
            };
            header?: never;
            path: {
                id: string;
                facet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetFaces"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mesh_preview_api_meshes__id__preview_png_get: {
        parameters: {
            query?: {
                view?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offscreen render of the mesh */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voxelize_project_api_projects__id__voxelize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoxelStats"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_selection_api_projects__id__resolve_selection_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaceSelection"] | components["schemas"]["FacetSelection"] | components["schemas"]["NormalSelection"] | components["schemas"]["PlaneSelection"] | components["schemas"]["PrimitiveSelection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedNodes"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInfo"][];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInfo"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_runs__id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInfo"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_stl_api_runs__id__result_stl_get: {
        parameters: {
            query?: {
                threshold?: number;
                smooth?: number;
                trim?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Isosurface of the density field */
            200: {
                headers: {
                    /** @description Why `trim=true` left the result untrimmed (joined with '; '); absent if fine */
                    "X-Topop-Warnings"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "model/stl": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_vti_api_runs__id__result_vti_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description VTK ImageData with the density field */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/xml": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_npz_api_runs__id__result_npz_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NumPy archive with the density field */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_stress_api_runs__id__stress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description [u32 nx][u32 ny][u32 nz][f32 von Mises per element], little-endian, C-order, 0 on inactive elements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_project_api_runs__id__project_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunExport"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInfo"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_preview_api_runs__id__preview_png_get: {
        parameters: {
            query?: {
                threshold?: number;
                view?: string;
                trim?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offscreen render of the result */
            200: {
                headers: {
                    /** @description Why `trim=true` left the result untrimmed (joined with '; '); absent if fine */
                    "X-Topop-Warnings"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
